name: 'Git matching commits'
author: Rick Meneely <rick@meneely.com>
branding:
  icon: filter
  color: purple
description: Returns a string with commits in the current repository with messages matching a regular expression"
inputs:
  start_tag_pattern:
    description: A regex to match the starting tag
    default: 'v[0-9]*.[0-9]*.[0-9]'
    required: false
  end_tag_pattern:
    description: A regex to match the ending tag (defaults to HEAD)
    default: ''
    required: false
  commit_message_pattern:
    description: A regex to match commit messages
    required: true
outputs:
  commits:
    description: 'Returns a comma separated list of found <commit> values'
    value: ${{ steps.git-matching-commits.outputs.commits }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt
      shell: bash
    - id: git-matching-commits
      run: |
        python ${{ github.action_path }}/git-matching-commits.py \
          --start_tag_pattern "${{ inputs.start_tag_pattern }}" \
          --end_tag_pattern "${{ inputs.end_tag_pattern }}" \
          --commit_message_pattern "${{ inputs.commit_message_pattern }}" \
          >> $GITHUB_OUTPUT
      shell: bash
